package worms.model;

import static org.junit.Assert.*;

import java.util.Random;
import org.junit.Before;
import org.junit.Test;

import worms.util.Util;

public class ProjectileTest {
	
	private static final double EPS = Util.DEFAULT_EPSILON;
	private Random random;
	private World world;
	private Worm worm;
	private static final double accuracyMapDimensions = 20.0 / 100;
	
	@Before
	public void setUp() throws Exception {
		boolean[][] map = {
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ true, true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true,
						true, true, true, true, true, true, true, true, true },
				{ false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false },
				{ false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false },
				{ false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false },
				{ false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false },
				{ false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false },
				{ false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false },
				{ false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false },
				{ false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false },
				{ false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false },
				{ false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false, false, false, false, false,
						false, false, false, false } };
		this.random = new Random(7357);
		this.world = new World(20.0, 20.0, map, random);
		this.worm = new Worm(1.0, 3.0, Math.PI/4, 1, "James O'Hare", true, world);
		world.addAsGameObject(worm);
	}

	@Test
	public void testConstructorLegalCaseRifle() {
		assertEquals(worm.getProjectile().getCoordinateX(),worm.getCoordinateX() + worm.getRadius()*Math.cos(worm.getDirection()),EPS);
		assertEquals(worm.getProjectile().getCoordinateY(),worm.getCoordinateY() + worm.getRadius()*Math.sin(worm.getDirection()),EPS);
		assertEquals(worm.getProjectile().getDirection(),worm.getDirection(),EPS);
		assertTrue(worm.getProjectile().getStatus());
		assertEquals(worm.getProjectile().getWorld(),world);
		assertEquals(worm.getProjectile().getDirection(),Math.PI/4,EPS);
		assertEquals(worm.getProjectile().getName(),"Rifle");
		assertEquals(worm.getProjectile().getMass(),0.010,EPS);
		assertEquals(worm.getProjectile().getCostActionPoints(), 10);
		assertEquals(worm.getProjectile().getLostHitPoints(), 20);
	}
	
	@Test
	public void testConstructorLegalCaseBazooka() {
		worm.selectWeapon();
		assertEquals(worm.getProjectile().getCoordinateX(),worm.getCoordinateX() + worm.getRadius()*Math.cos(worm.getDirection()),EPS);
		assertEquals(worm.getProjectile().getCoordinateY(),worm.getCoordinateY() + worm.getRadius()*Math.sin(worm.getDirection()),EPS);
		assertEquals(worm.getProjectile().getDirection(),worm.getDirection(),EPS);
		assertTrue(worm.getProjectile().getStatus());
		assertEquals(worm.getProjectile().getWorld(),world);
		assertEquals(worm.getProjectile().getDirection(),Math.PI/4,EPS);
		assertEquals(worm.getProjectile().getName(),"Bazooka");
		assertEquals(worm.getProjectile().getMass(),0.300,EPS);
		assertEquals(worm.getProjectile().getCostActionPoints(), 50);
		assertEquals(worm.getProjectile().getLostHitPoints(), 80);
	}
	
	@Test
	public void testDensity() {
		assertEquals(7800, Projectile.getDensity(), EPS);
	}
	
	@Test
	public void testGetName() {
		assertEquals("Rifle", worm.getProjectile().getName());
		worm.selectWeapon();
		assertEquals("Bazooka", worm.getProjectile().getName());
	}
	
	@Test
	public void testIsTerminated() {
		assertFalse(worm.getProjectile().isTerminated());
		worm.getProjectile().terminate();
		assertTrue(worm.getProjectile().isTerminated());
	}
	
	@Test
	public void testIfRadiusCorrectlyCalculated() {
		double mass = 1000;
		double radius = Math.pow(3*mass/(4*Math.PI*Projectile.getDensity()), 1.0/3);
		assertEquals(radius, Projectile.getRadius(mass),EPS);
	}
	
	@Test
	public void testGetMass() {
		Bazooka bazooka = new Bazooka(10,10,true,world,0);
		assertEquals(0.300,bazooka.getMass(),EPS);
	}
	
	@Test
	public void testGetLostHitPoints() {
		Rifle rifle = new Rifle(10,10,true,world,0);
		assertEquals(20,rifle.getLostHitPoints());
	}
	
	@Test
	public void testGetCostActionPoints() {
		Rifle rifle = new Rifle(10,10,true,world,0);
		assertEquals(10,rifle.getCostActionPoints());
	}
	
	@Test
	public void testYieldLegalCase() {
		worm.shoot(50);
		assertEquals(50, worm.getProjectile().getYield());
	}
	
	@Test (expected = ModelException.class)
	public void testYieldIllegalCase() {
		worm.shoot(150);
	}
	
	@Test
	public void testGetForceOfRifle() {
		assertEquals(1.5,worm.getProjectile().getForce(),EPS);
	}
	
	@Test
	public void getForceOfBazooka() {
		worm.selectWeapon();
		worm.shoot(0);
		assertEquals(2.5,worm.getProjectile().getForce(),EPS);
		worm.shoot(100);
		assertEquals(9.5,worm.getProjectile().getForce(),EPS);
	}
	
	@Test
	public void testShootingPorjectileHitsWorm() {
		Worm target = new Worm(3,5,0,1,"Torro",true,world);
		world.addAsGameObject(target);
		worm.shoot(50);
		worm.getProjectile().jump(Math.pow(10, -4));
		assertEquals(worm.getProjectile().getCoordinateX(), 3-Math.sqrt(2)/2,accuracyMapDimensions);
		assertEquals(worm.getProjectile().getCoordinateY(), 5-Math.sqrt(2)/2,accuracyMapDimensions);
		assertEquals(target.getHitPoints(),target.getMaximumHitPoints()-worm.getProjectile().getLostHitPoints());
	}
	
}
